### ISSUE TITLE
Add capability for multiple MAX31855

### ISSUE THREAD

**Issue by SV-Zanshin** [Zanduino/MAX31855#10]
**Describe what the feature request is and if it solves an issue or adds functionality**
Question asked by @billpurta Currently the library supports only one MAX31855 device although several may be present

**Describe the solution you'd like**
A such support or describe how it can be done with the current library

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by SV-Zanshin** [comment]
I only have one MAX31855 here, but if you modify the "Demo.ino" program to have 

```
MAX31855_Class MAX31855;  ///< Create an instance of MAX31855
MAX31855_Class SecondDevice; ///< Create another instance of MAX31855
```

In the definitions, and when you call "Second.Device.begin(SPI_CHIP_SELECT_2)" you need to specify another CS-Pin.
I think that should work without any issues at all.

**Comment by billpurta** [comment]
That worked!
Thank you.

Bill

**Comment by SV-Zanshin** [comment]
Excellent - have fun with the devices (and the library, of course).

**Comment by billpurta** [comment]
Hi Zanduino,

I forwarded on your github site to Kris Winer, owner of Tleracorp, who
makes the Grasshopper and other cool Mo+LoRa sensor and tracking boards to
share with his community in case others have similar issues.  Their website
is
https://www.tindie.com/products/tleracorp/grasshopper-loralorawan-development-board/
.

I have one last element to get to work on the Grasshopper, a single
Neopixel.  Seems Adafruit and other libraries all fail to produce any
signal output on any I/O lines I try.  I did reach out to Kris yesterday on
this but it is New Years holiday time as I didn't see anything for this in
his forums.

If you know of anyone who has a basic NeoPixel library that might work on
this MCU and is willing to let me give it a try I would greatly appreciate
it.  If any work, I will pass it along to you and the Tlera community as
well (love sharing good community work with others).

Thank you and Happy New Year!

Bill

**Comment by SV-Zanshin** [comment]
Hello Bill,

 

While I’d love to assist, I’ve never worked with the NeoPixel library before so I’m afraid I won’t be of any use for that. Right now I’m working on a good Arduino library for the MAX3244 (pulse and blood oxygen sensor)

 

Have a great New Year!

 

-Arnd.

**Comment by billpurta** [comment]
Hi Zanduino,

I understand and appreciate your help with the MAX31855 very much.

Be healthy and safe.

Bill

**Comment by SimonRafferty** [comment]
I'm not sure the above works.
`
MAX31855_Class MAX31855_1; ///< Create an instance of MAX31855
MAX31855_Class MAX31855_2;  ///< Create an instance of MAX31855
MAX31855_Class MAX31855_3;  ///< Create an instance of MAX31855
`
`
  if(MAX31855_1.begin(SPI_CHIP_SELECT_1)) {
    Serial.println("Thermocouple 1 Connected");
  } else {
    Serial.println("Thermocouple 1 FAILED");
  }
   
  if(MAX31855_2.begin(SPI_CHIP_SELECT_2)) {
    Serial.println("Thermocouple 2 Connected");
  } else {
    Serial.println("Thermocouple 2 FAILED");
  }
   
  if(MAX31855_3.begin(SPI_CHIP_SELECT_3)) {
    Serial.println("Thermocouple 3 Connected");
  } else {
    Serial.println("Thermocouple 3 FAILED");
  }
`
Returns:
Initializing MAX31855 sensor
Thermocouple 1 Connected
Thermocouple 2 FAILED
Thermocouple 3 FAILED

Whichever I try to connect to first will succeed - but the second & third always fail.
