### ISSUE TITLE
Typo in the demo

### ISSUE THREAD

**Issue by videobuff** [Zanduino/MAX31855#14]
## Expected Behavior

There is a typo in the demo. SO the compiler crashes

## Actual Behavior
see above
## Steps to Reproduce the Problem
Copy the demo and run it.

_Explain what needs to be done in order to reproduce the problem._
while (!MAX31855.begin(SPI_CHIP_SELECT,SPI_MISO,SPI_SYSTSEM_CLOCK)) // Software SPI for MAX31855
The tyope is in the SPI_SYSTSEM_CLOCK), which shoud be SPI_SYSTEM_CLOCK)

## Specifications

  - Library Version:
  - IDE Version:
  - Platform:
  - Subsystem:
  - _any other details needed to reproduce the problem_

**Comment by SV-Zanshin** [comment]
Hello @videobuff - The source code for the [demo.ino](https://github.com/Zanduino/MAX31855/blob/master/examples/Demo/Demo.ino) here on GitHub doesn't have that error.

Where did you source the incorrect **_demo.ino_** code?

**Comment by SV-Zanshin** [comment]
It seems as if the package in the Arduino IDE is outdated. I'll create a new package version so that error goes away.

**Comment by SV-Zanshin** [comment]
I've created the new package that include this fix

**Comment by SV-Zanshin** [comment]
Done.

**Comment by videobuff** [comment]
Thanks, not a big problem but I am working on a project for a SMD soldering station and intend to publish that.
B.t.w, do you think that i have to add levellers on SCK and CS, as well as a tri-state circuit on MISO ? 
I feed the sensors with 3.3.V from my ESP32 Wrover but i get somethimes very funny figures.
I just loaded the IDE again, went to the MAX31955 demo and it is still there - see the pic. Will try again later
<img width="1601" alt="Scherm­afbeelding 2023-12-13 om 12 43 57" src="https://github.com/Zanduino/MAX31855/assets/3132953/7c26344b-4d4a-4cd0-b0d3-6aa89e2fde2f">

**Comment by SV-Zanshin** [comment]
The Arduino package updates can take time, I think about a day, before they are added to the library manager.

I've not had any anomalous behaviour or readings on my various Atmel-Arduinos during testing. Perhaps the ESP32 platform is more sensitive due to its higher speed? But the circuit shouldn't really need additional hardware to function correctly.
